import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-base-100 w-screen text-base-content`}
      >
        <div className="navbar bg-base-100 p-5">
          <div className="flex">
            <a className="btn btn-ghost text-black text-xl">daisyUI</a>
          </div>
          <div className="flex-1 text-center space-x-10">
            <p className="text inline">All</p>
            <p className="text inline">Transaction</p>
            <p className="text inline">Analysic</p>
            <p className="text inline">Expenses</p>
            <p className="text inline">Spending</p>
          </div>
          <div className="flex gap-2">
            <input type="text" placeholder="Search" className="input input-bordered w-24 md:w-56" />
            <i className="ri-settings-line text-2xl mx-3 my-1"></i>
            <div className="dropdown dropdown-end">
              <div tabIndex={0} role="button" className="btn btn-ghost btn-circle avatar">
                <div className="w-10 rounded-full">
                  <img
                    alt="Tailwind CSS Navbar component"
                    src="https://img.daisyui.com/images/stock/photo-1534528741775-53994a69daeb.webp" />
                </div>
              </div>
              <ul
                tabIndex={0}
                className="menu menu-sm dropdown-content bg-base-100 rounded-box z-1 mt-3 w-52 p-2 shadow">
                <li>
                  <a className="justify-between">
                    Profile
                    <span className="badge">New</span>
                  </a>
                </li>
                <li><a>Settings</a></li>
                <li><a>Logout</a></li>
              </ul>
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
