import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-base-100 w-full text-base-content`}
      >
        <div className="navbar fixed md:relative shadow-sm md:shadow-none bg-base-100">
          <div className="navbar-start">
            <a className="btn btn-ghost text-xl">daisyUI</a>
          </div>
          <div className="hidden md:navbar-center">
            <a className="btn btn-ghost text-sm">All</a>
            <a className="btn btn-ghost text-sm">Transaction</a>
            <a className="btn btn-ghost text-sm">Analysic</a>
            <a className="btn btn-ghost text-sm">Expenses</a>
            <a className="btn btn-ghost text-sm">Spending</a>
          </div>
          <div className="navbar-end">
            <input type="text" placeholder="Search" className="input md:inline hidden  input-bordered w-24 md:mr-5 md:w-auto" />
            <i className="ri-settings-line md:mr-5 hidden md:inline"></i>
            <div className="dropdown dropdown-end">
              <div tabIndex={0} role="button" className="btn btn-ghost btn-circle avatar">
                <div className="w-10 rounded-full">
                  <img
                    alt="Tailwind CSS Navbar component"
                    src="https://img.daisyui.com/images/stock/photo-1534528741775-53994a69daeb.webp" />
                </div>
              </div>
              <ul
                tabIndex={0}
                className="menu menu-sm dropdown-content bg-base-100 rounded-box z-1 mt-5 w-52 p-2 shadow">
                <li>
                  <a className="justify-between">
                    Profile
                    <span className="badge">New</span>
                  </a>
                </li>
                <li><a>Settings</a></li>
                <li><a>Logout</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div className="pt-10 md:pt-0">
          {children}
        </div>
      </body>
    </html>
  );
}
